# Generated by Django 2.0.4 on 2018-05-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='uploads')),
                ('thumbnail_file', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
