version: '3'

services:
  forum_site:
    build:
      context: .
      dockerfile: Dockerfile
    image: forum_site
    container_name: forum_site
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - .:/app
