version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
      - 9229:9229 # default node debugger port
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
